void declarar(char *id);
void leer(char *id);
void escribir(char *id);
char *invertir(char *idEntrada);
char *multiplicar(char *idEntrada1, char *idEntrada2);
char *sumar(char *idEntrada1, char *idEntrada2);
char *restar(char *idEntrada1, char *idEntrada2);
char *dividir(char *idEntrada1, char *idEntrada2);
void guardar(char *idEntrada, char *idSalida);
void iniciar();
void detener();